/*Copyright (C) 2018-2022,2026 Marco M. Mosca

This file is part of periodic-point-cloud.

periodic-point-cloud is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

periodic-point-cloud is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with periodic-point-cloud. If not, see <https://www.gnu.org/licenses/>.
*/
#ifndef _PERIODICPOINTCLOUD_H
#define _PERIODICPOINTCLOUD_H

#include <vector>
#include <set>
#include <iostream>
#include <periodic_point_cloud/eigensupport.h>

/** 
 * @brief Represents a unique set of vector bases and their linear combinations.
 * 
 * Stores any number of vector bases and manages their linear combinations.
 * Coefficients for linear combinations are only integers.
 * 
 * Example:
 * ```
 * unsigned int n = 5;
 * std::vector<Eigen::Vector3d> generators = {
 *     Eigen::Vector3d(1,0,0),
 *     Eigen::Vector3d(0,1,0),
 *     Eigen::Vector3d(0,0,1)
 * }
 * PeriodicPointCloud ppc(generators.size());
 * for (auto& g : generators) {
 *     ppc.addGenerator(std::move(g));
 * }
 * ppc.updateCoefficientsForPositiveDirection(n);
 * ppc.updateCoefficientCombinations();
 * ```
 * Then, if you want to span the periodic point cloud from the generators 
 * and integer coefficients only call the following with no parameters:
 * ```
 * ppc.updateGeneratorCombinations();
 * ```
 * otherwise, create linear combinations from any vector collection
 * ```
 * std::vector<Eigen::Vector3d> points = {
 *     Eigen::Vector3d(0.5,0.5,0.5),
 *     Eigen::Vector3d(0.3,0.3,0.3)
 * }
 * ppc.updateGeneratorCombinationsForPoints(points);
 * ```
 * and get the entire point cloud in the following way
 * ```
 * std::vector<Eigen::Vector3d> pointcloud = ppc.getPointCloud();
 * ```
 */
class PeriodicPointCloud {

public:

	/**
	 * @brief Set of unique vector bases (or generators)
	 */
	std::set<Eigen::VectorXd, EigenVCompare> G;

	/**
	 * @brief Linear combinations of the unique set of vector bases (or generators)
	 */ 
	std::vector<Eigen::VectorXd> G_combinations;

	/**
	 * @brief Integer coefficients
	 */
	std::vector<int> C;

	/**
	 * @brief Integer coefficient permutations used for the linear combinations of the generators
	 */
	std::vector<Eigen::VectorXd> C_combinations;

	/**
	 * @brief Vectors' dimension
	 */
	int dimension;

	/**
     * @brief Creates a new periodic point cloud.
     * @param dimension The space dimension of all vectors generated by this instance.
     */
	PeriodicPointCloud(const int& d) : dimension{ d } {};

	/**
     * @brief Gets all the generated point cloud.
     * @return The Eigen::VectorXd stored in the generated point cloud.
     */
	std::vector<Eigen::VectorXd>& getPointCloud();

	/**
     * @brief Generate all the linear combinations from the internal generators and integer coefficients.
     * @return void.
     */
	void updateGeneratorCombinations();

	/**
     * @brief Generate the periodic point cloud from the given `points`.
	 * 
	 * Linear combinations of internal generators and integer coefficients are not added to the point cloud.
	 * @param points The collection of points that will be extended. Any point `p` that belongs to `R` is accepted.
     * @return void.
     */
	void updateGeneratorCombinationsForPoints(std::vector<Eigen::VectorXd> points);

	/**
     * @brief Extend the integer coefficients from a negative to a positive range of [-n, n]. 
	 * Linear combinations are updated accordingly.
	 * 
	 * @param n The range by which the point cloud is extended.
	 * @param points The collection of points that will be extended. Any point `p` that belongs to `R` is accepted.
     * @return void.
     */
	void extendBasisVectorsCoefficientsAndLinearCombinations(int n, std::vector<Eigen::VectorXd> points = {});

	/**
     * @brief Add integer coefficients in the range [-n, n] used for the linear combinations.
	 * 
	 * @param n The range of the integer coefficients which includes the negative domain [-n, n].
     * @return void.
     */
	void updateCoefficientsForEveryDirection(int n);

	/**
     * @brief Add integer coefficients in the range [0, n] used for the linear combinations.
	 * 
	 * @param n The range of the integer coefficients [0, n].
     * @return void.
     */
	void updateCoefficientsForPositiveDirection(int n);

	/**
     * @brief Add integer coefficients in the range [i, j] used for the linear combinations.
	 * 
	 * @param i The minimum value of the range for the integer coefficients.
	 * @param j The maximum value of the range for the integer coefficients.
     * @return void.
     */
	void updateCoefficientsFromRange(int i, int j);

	/**
     * @brief Generate all the coefficient permutations from the integer coefficients.
     * @return void.
     */
	void updateCoefficientCombinations(std::vector<int> to_filter = {}, Eigen::VectorXd v = {}, int n = -1);

	/**
     * @brief Add vector bases (or generators) which will span the entire space.
	 * 
	 * @param Eigen::VectorXd A vector basis or generator.
     * @return void.
     */
	void addGenerator(Eigen::VectorXd g);

	/**
     * @brief Clear the instance's data structures.
	 * 
	 * Remove Integer coefficients and their permutations, and vector bases and their linear combinations.
     * @return void.
     */
	void clear();

	/**
     * @brief Clear only the integer coefficients.
     * @return void.
     */
	void clearCoefficients();

	/**
     * @brief Clear the linear combinations and the integer coefficient permutations.
     * @return void.
     */
	void clearCombinations();
};

#endif // !_PERIODICPOINTCLOUD_H
